name: Build otter grader notebooks

on: workflow_dispatch

defaults:
  run:
    shell: bash
    working-directory: src/01

jobs:
  build:
    runs-on: ubuntu-20.04
 
    steps:
      - uses: actions/checkout@v3

      - name: Set up Otter Grader
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/ucbds-infra/otter-grader

      - name: Compile .ipynb
        run: |
          echo `pwd`
          echo `ls -ald`
          otter assign --v1 hw01.ipynb

      - name: Push to student notebook branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: student
          publish_dir: src/01/dist

