name: Build otter grader notebooks and push to student repo

on: workflow_dispatch

defaults:
  run:
    shell: bash
    working-directory: src/01

jobs:
  build:
    runs-on: ubuntu-20.04
 
    steps:
      - uses: actions/checkout@v3

      - name: Install pandoc for otter grader
        run: |
          sudo apt-get update -y
          sudo apt-get install -y pandoc texlive-xetex texlive-lang-chinese

      - name: Set up Otter Grader
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/ucbds-infra/otter-grader
          pip install nbconvert

      - name: Compile .ipynb
        run: |
          echo `pwd`
          echo `ls -ald`
          otter assign hw01.ipynb dist

      - name: Push to student notebook branch (for autograder files)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: student
          publish_dir: src/01/dist

      - name: Push to student notebook repo (for distribution to class)
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'src/01/dist/student'
          destination-github-username: 'rsprouse'
          destination-repository-name: 'otter-template-student'
          user-email: ronald@berkeley.edu
          target-branch: main
          target-directory: notebooks
